# yaml-language-server: $schema=./quartz/plugins/quartz-plugins.schema.json
configuration:
  pageTitle: "Sebas' knowledge garden"
  pageTitleSuffix: ""
  enableSPA: true
  enablePopovers: true
  analytics:
    provider: umami
    websiteId: "60a1ee55-e220-410d-aa67-3fb8280b5601"
  locale: en-US
  baseUrl: brain.sarrietav.dev
  ignorePatterns:
    - private
    - templates
    - .obsidian
  theme:
    fontOrigin: googleFonts
    cdnCaching: true
    typography:
      header: Merriweather
      body: Bricolage Grotesque
      code: Fira Code
    colors:
      lightMode:
        light: "#e8f0e8"
        lightgray: "#cfd8d3"
        gray: "#8a9b95"
        darkgray: "#4e5e58"
        dark: "#2c3e3b"
        secondary: "#4b6d63"
        tertiary: "#748c85"
        highlight: "rgba(75, 107, 95, 0.1)"
        textHighlight: "#b0c4b8"
      darkMode:
        light: "#1a2420"
        lightgray: "#3c4d46"
        gray: "#697c74"
        darkgray: "#ccd4ce"
        dark: "#e4ece8"
        secondary: "#5a7b6f"
        tertiary: "#748c85"
        highlight: "rgba(75, 107, 95, 0.15)"
        textHighlight: "#8fb3a3"
plugins: []